// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgbgeofszacgytlhdvtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nYmdlb2ZzemFjZ3l0bGhkdnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNDY0MzMsImV4cCI6MjA2MzcyMjQzM30.MeXbm4mD0_dFSW4XKrNhHmvaC_xDYcAKKqsIJsk9FvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);